### ISSUE TITLE
Add local htmlString support?

### ISSUE THREAD

**Issue by codwam** [jessesquires/JSQWebViewController#27]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQDataSourcesKit/blob/develop/README.md) and [documentation](http://www.jessesquires.com/JSQDataSourcesKit/).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/HowToContribute).
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQDataSourcesKit/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- Library version:
- OS version:
- Devices/Simulators:
- Reproducible in the demo project (Yes/No): 
- Any related issues:

## What happened?

            webView.loadHTMLString(htmlString, baseURL: nil)

**Comment by jessesquires** [comment]
Thanks @codwam ! 😄 

Can you explain this more?

**Comment by codwam** [comment]
```swift
fileprivate var htmlString: String?
    
    public convenience init(htmlString: String) {
// It shouldn't be invoke  ' url initialize '
        self.init(url: URL(string: "http://anonymous.com")!)
        
        self.htmlString = htmlString
    }
```
The current version suppor local html string to show no the url?
