### ISSUE TITLE
Dont deprecated it pls

### ISSUE THREAD

**Issue by paulocoutinhox** [jessesquires/JSQWebViewController#30]
Hi,

Dont deprecate it please, we use it on our projects, because we need support ios8.

If you want i can put all on my repository and maintain it.

Thanks.

**Comment by jessesquires** [comment]
Hi @prsolucoes ! 

That's fine. You can continue to use this and nothing will change.

The deprecation just means it won't be actively developed anymore (by me). 

I'm happy to accept pull requests for any changes/fixes you need.
