### ISSUE TITLE
Bug with topLayoutGuide and opaque navigation bars

### ISSUE THREAD

**Issue by kapoorsahil** [jessesquires/JSQWebViewController#4]
![simulator screen shot 24-sep-2015 1 21 17 pm](https://cloud.githubusercontent.com/assets/7577684/10068145/9d84b182-62bf-11e5-913c-16611585969e.png)

**Comment by jessesquires** [comment]
Thanks @kapoorsahil ! Can you provide more info?
- library version
- iOS version
- devices/simulators
- repro steps

**Comment by kapoorsahil** [comment]
I am using latest version, downloaded via Cocoapods. It's happening on both iOS 8 and iOS 9.On both device and simulator. I copy pasted your code from github, except for URL. 

```
_____________________________
```

**Comment by jessesquires** [comment]
Oh damn. I think I know the issue.

Try making your navigation bar translucent and see it this goes away. If it does, the issue is with `topLayoutGuide`.

**Comment by kapoorsahil** [comment]
Yeah, it fixes the problem.
